language: node_js
sudo: false
node_js:
  - 8.14.0
env:
  - NODE_ENV="test"
script:
  - npm test
  - npm run lint
before_script:
  - yarn db:setup:user
  - yarn db:reset
script:
  - yarn test
  - yarn enforce
  - yarn lint
